### ISSUE TITLE
choice is not jumping to label

### ISSUE THREAD

**Issue by Zyphon-22** [liana-pigeot/narrat#16]
For my game i wanted to have an ending where based on the players choice it will jump to a file and end. But no matter what i do the file is not being jumped i have added it to the config.json file under the scripts part and changed the files name multiple times, but nothing is working

this is the file 
![Screenshot 2022-05-05 09 13 55](https://user-images.githubusercontent.com/77876677/166885554-19b81876-7863-4171-86f1-0a7e9f6cd428.png)
![Screenshot 2022-05-05 09 13 45](https://user-images.githubusercontent.com/77876677/166885612-f76c85bf-a7ab-422f-8898-7a205162544f.png)

**Comment by liana-pigeot** [comment]
Hey, sorry for not replying earlier. I don't understand the problem exactly, what is it not jumping to?

Is "outside" the file where your game starts? I assume your problem then is that the `jump firstEnding`  bit isn't working.

One thing worth checking is if you have any errors in the browser console (right click on the page and "inspect" on chrome or firefox should open the devtools with a console in it). Maybe something is bugging and there would be an error appearing in the console in that case.

Outside of that, I think you also posted about your issue on itch.io and I replied with a [comment](https://itch.io/post/5991347) about how to upgrade your version of narrat. It could generally help as the latest version has a lot of bugs fixed and also improved debugging (it shows clearer errors when something is wrong) that would help you.

If despite all that you can't find the issue, I would need to see more of the game to see what's wrong as nothing looks obviously wrong to me based on what you posted.

**Comment by Zyphon-22** [comment]
Yeah it was giving me an error but almost as soon as i posted this everything started working again
